# -*- coding: utf-8 -*-
"""Simulador de maquina de pagamento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahMfvXOygzpOg29qXXSMsuSZt7ka_SD9
"""

from time import sleep
def valor_compra():
    valor = float(input('Digite o valor da compra R$ '))
    return valor

def forma_de_pagamento(valor):
  print(' 1 - Crédito')
  print(' 2 - Débito')
  while True:
    escolha = input('Escolha a forma de pagamento ')
    if escolha == '1':
      print(f'Crédito selecionado')
      return 'Crédito'
    elif escolha == '2':
      print(f'Débito selecionado')
      return 'Débito'
    elif escolha >= '3':
        print('Escolha opção 1 - Crédito ou 2 - Débito')
    elif escolha.isalpha():
        print('Apenas números: Opção 1 - Crédito ou 2 - Débito')

preco = valor_compra()
metodo = forma_de_pagamento(preco)

def parcelamento(pagamento, valor):
  print(f'Em quantas vezes quer parcelar a compra?')
  parcela = int(input('Digite o número de parcelas: '))
  parcelamento = valor/parcela
  print('Processando...')
  sleep(2)
  print(f'A compra de R$ {valor} será dividida em R$ {parcelamento:.2f}')

if metodo == 'Crédito':
  divisao = parcelamento(metodo, preco)
else:
  print('Processando...')
  print('A compra será paga no débito')
  sleep(2)

from time import sleep
def valor_compra():
    valor = float(input('Digite o valor da compra R$ '))
    return valor

def forma_de_pagamento(valor):
  print(' 1 - Crédito')
  print(' 2 - Débito')
  while True:
    escolha = input('Escolha a forma de pagamento ')
    if escolha == '1':
      print(f'Crédito selecionado')
      return 'Crédito'
    elif escolha == '2':
      print(f'Débito selecionado')
      return 'Débito'
    elif escolha >= '3':
        print('Escolha opção 1 - Crédito ou 2 - Débito')
    elif escolha.isalpha():
        print('Apenas números: Opção 1 - Crédito ou 2 - Débito')

preco = valor_compra()
metodo = forma_de_pagamento(preco)

def parcelamento(pagamento, valor):
  juros = 0
  print(f'Em quantas vezes quer parcelar a compra?')
  parcela = int(input('Digite o número de parcelas: '))
  if parcela >=13:
    juros = valor*0.01
    acressimo = valor + juros
  else:
    acressimo = valor
  parcelamento = acressimo/parcela
  print('Processando...')
  sleep(2)
  print(f'A compra de R$ {acressimo:.2f} será dividida em R$ {parcelamento:.2f}')

if metodo == 'Crédito':
  divisao = parcelamento(metodo, preco)
else:
  print('Processando...')
  print('A compra será paga no débito')
  sleep(2)

